server:
  port: 8005
mybatis:
  type-aliases-package: com.example.dp.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

  #Spring
spring:
  application:
      name: dp-test-provider-dppresent
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.19.241.61:3306/dp?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root123@
#    url: jdbc:mysql://localhost:3306/dp?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456

#配置eureka注册
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://172.17.0.2:7001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 172.19.241.99:8005

