server:
  port: 7001


eureka:
  instance:
    hostname: 172.19.241.99
  client:
    register-with-eureka: false #是否向注册中心注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/