server:
  port: 8001
mybatis:
  type-aliases-package: com.example.dp.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

  #Spring
spring:
  application:
      name: dp-test-provider-datamanager
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


    url: jdbc:mysql://localhost:3306/dp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


#配置eureka注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      #defaultZone: http://172.19.241.210:7001/eureka/
