server:
  port: 8002
mybatis:
  type-aliases-package: com.example.dp.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

  #Spring
spring:
  application:
      name: dp-test-provider-Forecast
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://localhost:3306/dp?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
    url: jdbc:mysql://172.19.241.99:3306/dp?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root123@


#配置eureka注册
eureka:
  client:
    service-url:
      defaultZone: http://172.19.241.99:7001/eureka/
      #defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
